data<-read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subset<-filter(data,Date=="1/2/2007" | Date=="2/2/2007")
xaxis <- dmy_hms(paste(subset$Date, subset$Time, sep=" "))
subset$Global_active_power<-as.numeric(subset$Global_active_power)
subset$Global_reactive_power<-as.numeric(subset$Global_reactive_power)
subset$Voltage<-as.numeric(subset$Voltage)
subset$Sub_metering_1<-as.numeric(subset$Sub_metering_1)
subset$Sub_metering_2<-as.numeric(subset$Sub_metering_2)
subset$Sub_metering_3<-as.numeric(subset$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(xaxis,subset$Global_active_power,type="l",xlab="",ylab = "Global Active Power")
plot(xaxis,subset$Voltage,type="l",xlab="datetime",ylab = "Voltage")
plot(xaxis,subset$Sub_metering_1,type="l",xlab="",ylab = "Energy Sub Metering")
lines(xaxis,subset$Sub_metering_2,col="red")
lines(xaxis,subset$Sub_metering_3,col="blue")
legend("topright",lty=1,lwd=2,bty="n",legend = c("sub_metering_1","sub_metering_2","sub_metering_3"),col=c("black","red","blue"))
plot(xaxis,subset$Global_reactive_power,type="l",xlab="datetime",ylab = "Global_rective_power")
dev.off()