data<-read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subset<-filter(data,Date=="1/2/2007" | Date=="2/2/2007")
xaxis <- dmy_hms(paste(subset$Date, subset$Time, sep=" "))
subset$Global_active_power<-as.numeric(subset$Global_active_power)
subset$Sub_metering_1<-as.numeric(subset$Sub_metering_1)
subset$Sub_metering_2<-as.numeric(subset$Sub_metering_2)
subset$Sub_metering_3<-as.numeric(subset$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(xaxis,subset$Sub_metering_1,type="l",xlab="",ylab = "Energy Sub Metering")
lines(xaxis,subset$Sub_metering_2,col="red")
lines(xaxis,subset$Sub_metering_3,col="blue")
legend("topright",lty=1,lwd=2,legend = c("sub_metering_1","sub_metering_2","sub_metering_3"),col=c("black","red","blue"))
dev.off()